from aiogram.types import InlineKeyboardButton, InlineKeyboardMarkup
from callback_underground import *
from bot import *

markup = InlineKeyboardMarkup(row_width=2)
item1 = InlineKeyboardButton(text="Автово", callback_data="avtovo")
item2 = InlineKeyboardButton(text="Академическая", callback_data="akademiceskaya")
item3 = InlineKeyboardButton(text="Адмиралтейская", callback_data="admiralteyskaya")
item4 = InlineKeyboardButton(text="Балтийская", callback_data="baltiyskaya")
item5 = InlineKeyboardButton(text="Бухаресткая", callback_data="buxarestkaya")
item6 = InlineKeyboardButton(text="Василеостровская", callback_data="vaska")
item7 = InlineKeyboardButton(text="Владимирская", callback_data="vladimir")
item8 = InlineKeyboardButton(text="Волковская", callback_data="volk")
item9 = InlineKeyboardButton(text="Выборгская", callback_data="viborg")
item10 = InlineKeyboardButton(text="Горьковская", callback_data="gork")
item11= InlineKeyboardButton(text="Гостиный двор", callback_data="gost_dvor")
item12 = InlineKeyboardButton(text="Гражданский проспект", callback_data="grajdan")
item13 = InlineKeyboardButton(text="Девяткино", callback_data="devat")
item14 = InlineKeyboardButton(text="Достоевская", callback_data="dost")
item15 = InlineKeyboardButton(text="Елизаровская", callback_data="elizar")
item16 = InlineKeyboardButton(text="Звёздная", callback_data="zvezdnaya")
item17 = InlineKeyboardButton(text="вперед-->", callback_data='right_arrow')
markup.add(item1, item2, item3, item4, item5, item9, item16, item15,item14,item13, item8,item12,item7,item10, item11, item6, item17)




markup2 = InlineKeyboardMarkup(row_width=2)
item18 = InlineKeyboardButton(text="Невский проспект", callback_data="nevskiy")
item19 = InlineKeyboardButton(text="Звенигородская", callback_data="zveni")
item20 = InlineKeyboardButton(text="Кировский завод", callback_data="kirov")
item21 = InlineKeyboardButton(text="Комендантский проспект", callback_data="komenda")
item22 = InlineKeyboardButton(text="Крестовский остров", callback_data="krest")
item23 = InlineKeyboardButton(text="Купчино", callback_data="kupcino")
item24 = InlineKeyboardButton(text="Ладожская", callback_data="lado")
item25 = InlineKeyboardButton(text="Ленинский проспект", callback_data="lenin")
item26 = InlineKeyboardButton(text="Лесная", callback_data="les")
item27 = InlineKeyboardButton(text="Лиговский проспект", callback_data="liga")
item28 = InlineKeyboardButton(text="Ломоносовская", callback_data="lomo")
item29 = InlineKeyboardButton(text="Маяковская", callback_data="mayak")
item30 = InlineKeyboardButton(text="Международная", callback_data="mej")
item31 = InlineKeyboardButton(text="Московская", callback_data="moscow")
item32 = InlineKeyboardButton(text="Московские ворота", callback_data="mosc_gate")
item33 = InlineKeyboardButton(text="Нарвская", callback_data="narv")
item34 = InlineKeyboardButton(text="<--назад", callback_data='left_arrow')
item35 = InlineKeyboardButton(text="вперед-->", callback_data='right_arrow2')
markup2.add(item18, item19, item20, item21, item33, item31, item33, item30, item25, item28, item27, item26, item29, item22, item32, item23, item34, item35)



markup3 = InlineKeyboardMarkup(row_width=2)
item36 = InlineKeyboardButton(text="Новочеркасская", callback_data="novo")
item37 = InlineKeyboardButton(text="Обводный канал", callback_data="ok")
item38 = InlineKeyboardButton(text="Обухово", callback_data="obux")
item39 = InlineKeyboardButton(text="Озерки", callback_data="ozerki")
item40 = InlineKeyboardButton(text="Парк Победы", callback_data="pb")
item41 = InlineKeyboardButton(text="Парнас", callback_data="parnas")
item42 = InlineKeyboardButton(text="Петроградская", callback_data="petro")
item43 = InlineKeyboardButton(text="Пионерская", callback_data="pioner")
item44 = InlineKeyboardButton(text="Площадь Александра Невского I", callback_data="pan")
item45 = InlineKeyboardButton(text="Площадь Восстания", callback_data="pv")
item46 = InlineKeyboardButton(text="Площадь Ленина", callback_data="pl")
item47 = InlineKeyboardButton(text="Площадь Мужества", callback_data="pm")
item48 = InlineKeyboardButton(text="Политехническая", callback_data="pol")
item49 = InlineKeyboardButton(text="Приморская", callback_data="prim")
item50 = InlineKeyboardButton(text="Пролетарская", callback_data="proletar")
item51 = InlineKeyboardButton(text="Проспект Большевиков", callback_data="pros_bol")
item52 = InlineKeyboardButton(text="<--назад", callback_data='left_arrow2')
item53 = InlineKeyboardButton(text="вперед-->", callback_data='right_arrow3')
markup3.add(item36, item37, item38, item39, item40, item41, item42, item43, item44, item45, item46, item47, item48, item49, item50, item51, item52, item53)



markup4 = InlineKeyboardMarkup(row_width=2)
item54 = InlineKeyboardButton(text="Проспект Ветеранов", callback_data="vet")
item55 = InlineKeyboardButton(text="Проспект Просвещения", callback_data="pp")
item56 = InlineKeyboardButton(text="Пушкинская", callback_data="pusk")
item57 = InlineKeyboardButton(text="Рыбацкое", callback_data="riba")
item58 = InlineKeyboardButton(text="Садовая", callback_data="sad")
item59 = InlineKeyboardButton(text="Спасская", callback_data="spas")
item60 = InlineKeyboardButton(text="Спортивная", callback_data="saport")
item61 = InlineKeyboardButton(text="Старая Деревня", callback_data="sd")
item62 = InlineKeyboardButton(text="Технологический институт", callback_data="ti")
item63 = InlineKeyboardButton(text="Удельная", callback_data="udel")
item64 = InlineKeyboardButton(text="Улица Дыбенко", callback_data="ud")
item65 = InlineKeyboardButton(text="Фрунзенская", callback_data="frun")
item66 = InlineKeyboardButton(text="Чёрная речка", callback_data="cr")
item67 = InlineKeyboardButton(text="Чернышевская", callback_data="cher")
item68 = InlineKeyboardButton(text="Чкаловская", callback_data="chkal")
item69 = InlineKeyboardButton(text="Электросила", callback_data="electro")
item70 = InlineKeyboardButton(text="<--назад", callback_data='left_arrow3')
markup4.add(item54, item55, item56, item57, item58, item59, item60, item61, item62, item63, item64, item65, item66, item67, item68, item69, item70)